language: node_js
cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

install: true

script:
  - sh -x ./scripts/_build.sh -e

after_success:
  - 'if [[ "$TRAVIS_SECURE_ENV_VARS" = "true" ]]; then
       npm prune;
       npm run semantic-release;
     fi'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
